// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hashmaputil.actions;

import java.util.Set;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import hashmaputil.implementation.HashMapUtil;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Add entity object list into the Set that specified by the handle.
 * You can get handle by CreateHashSet action.
 * It returns count that it did put.
 * 
 */
public class AddToSetFromList extends UserAction<java.lang.Long>
{
	private final java.lang.String Handle;
	private final java.util.List<IMendixObject> ContentList;

	public AddToSetFromList(
		IContext context,
		java.lang.String _handle,
		java.util.List<IMendixObject> _contentList
	)
	{
		super(context);
		this.Handle = _handle;
		this.ContentList = _contentList;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		Set<IMendixObject> mySet = HashMapUtil.getContentSet(Handle);
		if (mySet == null) {
			throw new RuntimeException("Set's handle(" + Handle + ") is invalid.");
		} else {
			int added = 0;
			for (IMendixObject mo : ContentList) {
				if (mySet.add(mo)) {
					added++;
				}
			}
			return (long)added;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddToSetFromList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
