// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hashmaputil.actions;

import java.util.HashSet;
import java.util.UUID;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import hashmaputil.implementation.HashMapUtil;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Creates a new HashSet on ThreadLocal and returns its handle string.
 * You can use other actions by returned handle string.
 * 
 */
public class CreateHashSet extends UserAction<java.lang.String>
{
	public CreateHashSet(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		UUID uuid = UUID.randomUUID();
		String handle = uuid.toString();
		HashMapUtil.putContentSet(handle, new HashSet<IMendixObject>());
		return handle;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateHashSet";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
