// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hashmaputil.actions;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import hashmaputil.implementation.HashMapUtil;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Creates a new LRU cache mode LinkedHashMapon ThreadLocal and returns its handle string.
 * You can use other actions by returned handle string.
 * 
 */
public class CreateLinkedHashMapAsLRUCache extends UserAction<java.lang.String>
{
	private final java.lang.Long CacheSize;

	public CreateLinkedHashMapAsLRUCache(
		IContext context,
		java.lang.Long _cacheSize
	)
	{
		super(context);
		this.CacheSize = _cacheSize;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		UUID uuid = UUID.randomUUID();
		String handle = uuid.toString();
		HashMapUtil.putLocalContentMap(handle, //
				new LinkedHashMap<String, IMendixObject>(16, (float) 0.75, true) {
					protected boolean removeEldestEntry(Map.Entry eldest) {
						return size() > CacheSize;
					}
				});
		return handle;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateLinkedHashMapAsLRUCache";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
