// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hashmaputil.actions;

import java.util.Map;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import hashmaputil.implementation.HashMapUtil;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Put a key-value-list pair into the hashmap that specified by the handle.
 * You can get handle by CreateHashMap action.
 * 
 * Once you put the entity-list by this action,  you can't use ToValueListFromHashMap action to that Map hereafter, because Mendix can't handle list's list.
 * It returns always 'true'.
 * 
 */
public class PutListToHashMap extends UserAction<java.lang.Boolean>
{
	private final java.lang.String Handle;
	private final java.lang.String Key;
	private final java.util.List<IMendixObject> ValueObjectList;

	public PutListToHashMap(
		IContext context,
		java.lang.String _handle,
		java.lang.String _key,
		java.util.List<IMendixObject> _valueObjectList
	)
	{
		super(context);
		this.Handle = _handle;
		this.Key = _key;
		this.ValueObjectList = _valueObjectList;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Map myMap = HashMapUtil.getContentMap(Handle);
		if (myMap == null) {
			throw new RuntimeException("Hash Map Handle(" + Handle + ") is invalid.");
		} else {
			myMap.put(Key, ValueObjectList);
			return true;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PutListToHashMap";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
