// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hashmaputil.actions;

import java.util.HashMap;
import java.util.Map;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Put a key-value pair into the Context(the scope of the current request).
 */
public class PutToContext extends UserAction<java.lang.Void>
{
	private final java.lang.String Key;
	private final IMendixObject ValueObject;

	public PutToContext(
		IContext context,
		java.lang.String _key,
		IMendixObject _valueObject
	)
	{
		super(context);
		this.Key = _key;
		this.ValueObject = _valueObject;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		Map contextDataMap =  getContext().getData();
		Map<String, IMendixObject> myMap = (Map)contextDataMap.get(PutToContext.class.getName());
		if (myMap == null) {
			myMap = new HashMap<String, IMendixObject>();
			contextDataMap.put(PutToContext.class.getName(), myMap);
		}
		myMap.put(Key, ValueObject);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PutToContext";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
