// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hashmaputil.actions;

import java.util.Map;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import hashmaputil.implementation.HashMapUtil;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Put key-value pairs list into the hashmap that specified by the handle.
 * You can get handle by CreateHashMap action.
 * It returns count that it did put.
 * 
 */
public class PutToHashMapFromList extends UserAction<java.lang.Long>
{
	private final java.lang.String Handle;
	private final java.util.List<IMendixObject> EntityList;
	private final java.lang.String KeyAttributeName;

	public PutToHashMapFromList(
		IContext context,
		java.lang.String _handle,
		java.util.List<IMendixObject> _entityList,
		java.lang.String _keyAttributeName
	)
	{
		super(context);
		this.Handle = _handle;
		this.EntityList = _entityList;
		this.KeyAttributeName = _keyAttributeName;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		Map<String, IMendixObject> myMap = HashMapUtil.getContentMap(Handle);
		if (myMap == null) {
			throw new RuntimeException("Hash Map Handle(" + Handle + ") is invalid.");
		} else {
			for (IMendixObject mo : EntityList) {
				myMap.put(mo.getValue(getContext(), KeyAttributeName).toString(), mo);
			}
			return (long)EntityList.size();
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PutToHashMapFromList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
