// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hashmaputil.actions;

import java.util.Map;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Remove a key-value pair from the Context(the scope of the current request).
 */
public class RemoveFromContextAndGet extends UserAction<IMendixObject>
{
	private final java.lang.String Key;
	private final java.lang.String ValueType;

	public RemoveFromContextAndGet(
		IContext context,
		java.lang.String _key,
		java.lang.String _valueType
	)
	{
		super(context);
		this.Key = _key;
		this.ValueType = _valueType;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		Map contextDataMap =  getContext().getData();
		Map<String, IMendixObject> myMap = (Map)contextDataMap.get(PutToContext.class.getName());
		if (myMap == null) {
			return null;
		} else {
			return myMap.remove(Key);
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RemoveFromContextAndGet";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
