// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hashmaputil.actions;

import java.util.Map;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Remove a key-value pair from the Context(the scope of the current request).
 */
public class RemoveFromContext extends UserAction<java.lang.Boolean>
{
	private final java.lang.String Key;

	public RemoveFromContext(
		IContext context,
		java.lang.String _key
	)
	{
		super(context);
		this.Key = _key;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Map contextDataMap =  getContext().getData();
		Map<String, IMendixObject> myMap = (Map)contextDataMap.get(PutToContext.class.getName());
		if (myMap == null) {
			return false;
		}
		IMendixObject o = myMap.remove(Key);
		return o != null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RemoveFromContext";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
