// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hashmaputil.actions;

import java.util.Map;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import hashmaputil.implementation.HashMapUtil;
import hashmaputil.proxies.KeyWrapper;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Get key list of the hashmap that specified by the handle.
 * You can get handle by CreateHashMap action.
 * 
 */
public class ToKeyListFromHashMap extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String Handle;

	public ToKeyListFromHashMap(
		IContext context,
		java.lang.String _handle
	)
	{
		super(context);
		this.Handle = _handle;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		Map<String, IMendixObject> myMap = HashMapUtil.getContentMap(Handle);
		if (myMap == null) {
			throw new RuntimeException("Hash Map Handle(" + Handle + ") is invalid.");
		} else {
			java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>();
			for (String s : myMap.keySet()) {
				KeyWrapper kw = new KeyWrapper(this.getContext());
				kw.setKey(s);
				list.add(kw.getMendixObject());
			}
			return list;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ToKeyListFromHashMap";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
