// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hashmaputil.actions;

import java.util.Set;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import hashmaputil.implementation.HashMapUtil;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Get content list of the Set that specified by the handle.
 * You can get handle by CreateHashSet action.
 * 
 */
public class ToListFromSet extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String Handle;
	private final java.lang.String ContentType;

	public ToListFromSet(
		IContext context,
		java.lang.String _handle,
		java.lang.String _contentType
	)
	{
		super(context);
		this.Handle = _handle;
		this.ContentType = _contentType;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		Set<IMendixObject> mySet = HashMapUtil.getContentSet(Handle);
		if (mySet == null) {
			throw new RuntimeException("Set's handle(" + Handle + ") is invalid.");
		} else {
			java.util.List<IMendixObject> list = new java.util.ArrayList<IMendixObject>(mySet);
			return list;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ToListFromSet";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
