// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package adminmodule.actions;

import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.Scanner;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JV_AccessToken_Get extends UserAction<java.lang.String>
{
	private final java.lang.String client_id;
	private final java.lang.String client_secret;
	private final java.lang.String url;

	public JV_AccessToken_Get(
		IContext context,
		java.lang.String _client_id,
		java.lang.String _client_secret,
		java.lang.String _url
	)
	{
		super(context);
		this.client_id = _client_id;
		this.client_secret = _client_secret;
		this.url = _url;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		
URL endpoint = new URL(url);
HttpURLConnection conn = (HttpURLConnection) endpoint.openConnection();

conn.setRequestMethod("POST");
conn.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
conn.setDoOutput(true);

String body = "grant_type=client_credentials"
			+ "&client_id=" + client_id
			+ "&client_secret=" + client_secret;

try (OutputStream os = conn.getOutputStream()) {
	byte[] input = body.getBytes(StandardCharsets.UTF_8);
	os.write(input, 0, input.length);
}

int responseCode = conn.getResponseCode();
if (responseCode == HttpURLConnection.HTTP_OK) {
	try (Scanner scanner = new Scanner(conn.getInputStream(), StandardCharsets.UTF_8.name())) {
		return scanner.useDelimiter("\\A").next();
	}
} else {
	throw new RuntimeException("Failed : HTTP error code : " + responseCode);
}

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JV_AccessToken_Get";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
