// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import * as urlParse from 'url-parse';

// BEGIN EXTRA CODE

async function createMxObj(entity) {
	return new Promise(function(resolve,reject) {
		mx.data.create({
			entity: entity,
			callback: function(obj) {
				resolve(obj);
			},
			error: function(e) {
				reject("Could not create object: "+entity, e);
			}
		}
		);
	});
}

// END EXTRA CODE

/**
 * @param {string} urlString
 * @returns {Promise.<MxObject>}
 */
export async function URLParse(urlString) {
	// BEGIN USER CODE
	// Parse the URL
const parsedUrl = urlParse(urlString);

// Access parsed components
const obj = await createMxObj("URLUtilities.URLParse");
	obj.set("Protocol", parsedUrl.protocol);
	obj.set("Host", parsedUrl.host);
	obj.set("Port", parsedUrl.port);
	obj.set("Hostname", parsedUrl.hostname);
	obj.set("Path", parsedUrl.pathname);
	obj.set("Query", parsedUrl.query);
	obj.set("Hash", parsedUrl.hash);
	obj.set("Username", parsedUrl.username);
	obj.set("Password", parsedUrl.password);
	obj.set("Origin", parsedUrl.origin);
	
	return obj;
	
	// END USER CODE
}
