// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package login.actions;

import com.mendix.core.Core;
import com.mendix.m2ee.api.IMxRuntimeResponse;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.ISession;
import com.mendix.systemwideinterfaces.core.UserAction;

public class LoginUser extends UserAction<java.lang.Boolean>
{
	/** @deprecated use user.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __user;
	private final system.proxies.User user;
	private final java.lang.String currentSessionId;

	public LoginUser(
		IContext context,
		IMendixObject _user,
		java.lang.String _currentSessionId
	)
	{
		super(context);
		this.__user = _user;
		this.user = _user == null ? null : system.proxies.User.initialize(getContext(), _user);
		this.currentSessionId = _currentSessionId;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		IMxRuntimeResponse response= this.getContext().getRuntimeResponse().get();

        IContext systemContext = Core.createSystemContext();
		
        ISession newSession = Core.login(user.getName(), user.getName(), currentSessionId);
        response.addCookie("XASSESSIONID", newSession.getId().toString(),"/" ,"" ,-1, true, true );
        response.addCookie("XASID", "0." + Core.getXASId(),"/" ,"" ,-1, true, true);
	
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "LoginUser";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
