// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package loginmodule.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.ISession;
import com.mendix.systemwideinterfaces.core.UserAction;

import system.proxies.Session;

public class JV_DeleteSession extends UserAction<java.lang.Boolean>
{
	private final java.lang.String sessionId;

	public JV_DeleteSession(
		IContext context,
		java.lang.String _sessionId
	)
	{
		super(context);
		this.sessionId = _sessionId;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		// throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		
		java.util.Collection<? extends ISession> activeSessions = Core.getActiveSessions();

        for (ISession session : activeSessions) {
            if (session.getId().toString().equals(sessionId)) {
                Core.logout(session);
				
                return true;
            }
        }
		return false;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JV_DeleteSession";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
