// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package loginmodule.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.ISession;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JV_Session_CloseByUser extends UserAction<java.lang.Boolean>
{
	private final java.lang.String userName;

	public JV_Session_CloseByUser(
		IContext context,
		java.lang.String _userName
	)
	{
		super(context);
		this.userName = _userName;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE

		java.util.Collection<? extends ISession> sessionList = Core.getActiveSessions();
		boolean hadActiveSession = false;
		for (ISession iSession : sessionList) {
			// iSession.getUserName().equals(userName);
			if (iSession.getUserName().equals(userName)) {
			 	Core.logout(iSession);
				hadActiveSession = true;
			}
		}
		return hadActiveSession;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JV_Session_CloseByUser";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
