// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package loginmodule.actions;

import java.util.Collections;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import mainmodule.proxies.User;
import system.proxies.UserRole;

public class JV_User_Create extends UserAction<IMendixObject>
{
	private final java.lang.String email;
	/** @deprecated use userRole.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __userRole;
	private final system.proxies.UserRole userRole;

	public JV_User_Create(
		IContext context,
		java.lang.String _email,
		IMendixObject _userRole
	)
	{
		super(context);
		this.email = _email;
		this.__userRole = _userRole;
		this.userRole = _userRole == null ? null : system.proxies.UserRole.initialize(getContext(), _userRole);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		LOG.warn("EMAIL1: " + email);
		User user = new User(getContext());
		LOG.warn("EMAIL2: " + email);
		user.setEmail(email);
		user.setPassword(email);
		user.setName(email);
		
		// List<IMendixObject> roles = Core.createXPathQuery("//System.UserRole[Name = 'User']")
		// 		.setAmount(1)
		// 		.execute(getContext());

		// if (roles.isEmpty()) {
		// 	throw new com.mendix.systemwideinterfaces.MendixRuntimeException("UserRole was not found");
		// }

		// IMendixObject userRole = roles.get(0);
		user.setUserRoles(Collections.singletonList(userRole));
		// user.getMendixObject().setValue(getContext(), "System.UserRoles", Collections.singletonList(userRole));
		Core.commit(getContext(), user.getMendixObject());
		return user.getMendixObject();

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JV_User_Create";
	}

	// BEGIN EXTRA CODE
	public static ILogNode LOG = Core.getLogger("JavaAction");
	// END EXTRA CODE
}
