// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
function generateRandomString(length) {
    let text = '';
    const possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    for (let i = 0; i < length; i++) {
        text += possible.charAt(Math.floor(Math.random() * possible.length));
    }
    return text;
}
// END EXTRA CODE

/**
 * @param {Big} user_id
 * @param {string} redirect_url
 * @param {string} scope
 * @param {string} client_id
 * @returns {Promise.<void>}
 */
export async function JS_Redirect(user_id, redirect_url, scope, client_id) {
	// BEGIN USER CODE
	// const client_id = 'd251fca64aba4d9bb23b6d45f30ee0b6'; 
// const scope = 'user-read-private user-read-email user-top-read user-read-currently-playing user-read-recently-played user-read-playback-state user-modify-playback-state';



const queryParams = new URLSearchParams({
    response_type: 'code',
    client_id: client_id,
    scope: scope,
    redirect_uri: redirect_url,
    state: user_id,
	show_dialog: true
});

const spotifyAuthUrl = `https://accounts.spotify.com/authorize?${queryParams.toString()}`;

window.location.href = spotifyAuthUrl;


return Promise.resolve();

	// END USER CODE
}
