// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package jwt.actions;

import java.math.BigInteger;
import java.security.KeyFactory;
import java.security.interfaces.RSAPrivateKey;
import java.security.interfaces.RSAPublicKey;
import java.security.spec.RSAPublicKeySpec;
import com.mendix.systemwideinterfaces.core.IContext;
import jwt.helpers.RSAKeyPairGenerator;
import jwt.helpers.RSAKeyPairReader;
import jwt.proxies.JWTRSAPublicKey;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Use this action to instantiate a public key in case your key pair has been generated by a third party.
 */
public class GenerateRSAPublicKey extends UserAction<IMendixObject>
{
	private final java.lang.String modulus;
	private final java.lang.String publicExponent;
	private final java.lang.String issuer;
	private final java.lang.String subject;
	private final java.lang.Long yearsValidity;
	/** @deprecated use privateKey.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __privateKey;
	private final jwt.proxies.JWTRSAPrivateKey privateKey;

	public GenerateRSAPublicKey(
		IContext context,
		java.lang.String _modulus,
		java.lang.String _publicExponent,
		java.lang.String _issuer,
		java.lang.String _subject,
		java.lang.Long _yearsValidity,
		IMendixObject _privateKey
	)
	{
		super(context);
		this.modulus = _modulus;
		this.publicExponent = _publicExponent;
		this.issuer = _issuer;
		this.subject = _subject;
		this.yearsValidity = _yearsValidity;
		this.__privateKey = _privateKey;
		this.privateKey = _privateKey == null ? null : jwt.proxies.JWTRSAPrivateKey.initialize(getContext(), _privateKey);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		KeyFactory keyFactory = KeyFactory.getInstance("RSA");
		RSAPublicKeySpec publicKeySpec = new RSAPublicKeySpec(new BigInteger(modulus), new BigInteger(publicExponent));
		RSAPublicKey rsaPublicKey = (RSAPublicKey) keyFactory.generatePublic(publicKeySpec);
		
		RSAKeyPairReader rsaKeyPairReader = new RSAKeyPairReader();
		RSAPrivateKey rsaPrivateKey = rsaKeyPairReader.getPrivateKey(this.getContext(), privateKey);
		
		RSAKeyPairGenerator rsaKeyPairGenerator = new RSAKeyPairGenerator();
		JWTRSAPublicKey publicKey = rsaKeyPairGenerator.generatePublic(this.getContext(), "public.der", rsaPublicKey, rsaPrivateKey, issuer, subject, Math.toIntExact(yearsValidity));
		
		return publicKey.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateRSAPublicKey";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
