// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package expertutils.actions;

import java.math.BigDecimal;
import com.mendix.systemwideinterfaces.core.IContext;
import expertutils.DistanceUtils;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * The CalculateHaversineDistance Java action calculates the great-circle distance between two points on the Earth's surface using the Haversine formula. This formula accounts for the Earth's curvature and provides an accurate distance measurement based on latitude and longitude.
 * 
 * The function takes in the geographical coordinates (latitude and longitude) of two positions (A and B) and returns the distance between them in meters.
 */
public class CalculateHaversineDistance extends UserAction<java.math.BigDecimal>
{
	private final java.lang.String PositionALongitude;
	private final java.lang.String PositionALatitude;
	private final java.lang.String PositionBLongitude;
	private final java.lang.String PositionBLatitude;

	public CalculateHaversineDistance(
		IContext context,
		java.lang.String _positionALongitude,
		java.lang.String _positionALatitude,
		java.lang.String _positionBLongitude,
		java.lang.String _positionBLatitude
	)
	{
		super(context);
		this.PositionALongitude = _positionALongitude;
		this.PositionALatitude = _positionALatitude;
		this.PositionBLongitude = _positionBLongitude;
		this.PositionBLatitude = _positionBLatitude;
	}

	@java.lang.Override
	public java.math.BigDecimal executeAction() throws Exception
	{
		// BEGIN USER CODE
		double distance = DistanceUtils.haversineDistance(PositionALongitude, PositionALatitude, PositionBLongitude, PositionBLatitude);
		
		return BigDecimal.valueOf(distance);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CalculateHaversineDistance";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
