// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package expertutils.actions;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * The ExecuteNonQuerySQL Java action executes a non-query SQL statement directly on the Mendix database.
 * 
 * This action is useful for modifying data (e.g., INSERT, UPDATE, DELETE) or executing DDL operations (e.g., creating or altering tables).
 * 
 * ⚠ Use with caution! Direct SQL execution can bypass Mendix security, cause inconsistencies, and is database-specific.
 */
public class ExecuteNonQuerySQL extends UserAction<java.lang.Long>
{
	private final java.lang.String Sql;

	public ExecuteNonQuerySQL(
		IContext context,
		java.lang.String _sql
	)
	{
		super(context);
		this.Sql = _sql;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode logger = Core.getLogger("ExpertUtils");

	    logger.debug("Executing SQL statement: " + this.Sql);

	    int result = Core.dataStorage().executeWithConnection(connection -> {
	        try (PreparedStatement stmt = connection.prepareStatement(this.Sql)) {
	            return stmt.executeUpdate(); 
	        } catch (SQLException e) {
	            logger.error("SQL execution failed: " + e.getMessage(), e);
	            throw new MendixRuntimeException("SQL execution error", e);
	        }
	    });

	    return Long.valueOf(result);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExecuteNonQuerySQL";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
