// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package expertutils.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * The GetObjectAttributeValueByName Java action retrieves the value of an attribute from a given Mendix object based on its attribute name and returns it as a string.
 * 
 * This Java action enables dynamic access to attribute values without hardcoding attribute retrieval in microflows, making it useful for generic entity processing scenarios.
 */
public class GetObjectAttributeValueByName extends UserAction<java.lang.String>
{
	private final IMendixObject MxObject;
	private final java.lang.String AttributeName;

	public GetObjectAttributeValueByName(
		IContext context,
		IMendixObject _mxObject,
		java.lang.String _attributeName
	)
	{
		super(context);
		this.MxObject = _mxObject;
		this.AttributeName = _attributeName;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return MxObject.getValue(getContext(), AttributeName).toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetObjectAttributeValueByName";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
