// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package expertutils.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * The GetObjectByGUID Java action retrieves an object from the Mendix database using its Global Unique Identifier (GUID).
 * 
 * This is useful when you need to retrieve a specific object directly by its GUID.
 */
public class GetObjectByGUID extends UserAction<IMendixObject>
{
	private final IMendixObject Entity;
	private final java.lang.String ObjectGUID;

	public GetObjectByGUID(
		IContext context,
		IMendixObject _entity,
		java.lang.String _objectGUID
	)
	{
		super(context);
		this.Entity = _entity;
		this.ObjectGUID = _objectGUID;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		java.util.List<IMendixObject> mxObjects = com.mendix.core.Core.createXPathQuery("//" + Entity + "[id=" + ObjectGUID + "]").execute(getContext());
		if(mxObjects == null || mxObjects.isEmpty())
		{
			return null;
		}
		else {
			IMendixObject mxObj = mxObjects.get(0);
			return mxObj;					
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetObjectByGUID";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
