// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package expertutils.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * The RetrieveListItemByIndex Java action extracts an element from a list at a specified index. This is useful when working with lists where you need to fetch a particular item based on its position.
 * 
 * The function takes in a list of objects and an index (zero-based) and returns the corresponding item from the list.
 */
public class RetrieveListItemByIndex extends UserAction<IMendixObject>
{
	private final java.util.List<IMendixObject> List;
	private final java.lang.Long Index;

	public RetrieveListItemByIndex(
		IContext context,
		java.util.List<IMendixObject> _list,
		java.lang.Long _index
	)
	{
		super(context);
		this.List = _list;
		this.Index = _index;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		return List.get(Index.intValue());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RetrieveListItemByIndex";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
