// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hashmap.actions;

import java.util.HashMap;
import com.mendix.systemwideinterfaces.core.IContext;
import hashmap.implementation.MxHashMapHelper;
import hashmap.implementation.MxHashMapImpl;
import hashmap.proxies.AbstractMxHashMapEntry;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Adds an entry to the map. Returns the entry object previously related to the given key, can be empty. Provide the entity type so that the returned object is of the right type. If the entity type does not match the entity type given at creation of the map, this will throw a runtime error.
 */
public class JAVA_Hashmap_PutEntry extends UserAction<IMendixObject>
{
	/** @deprecated use Map.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Map;
	private final hashmap.proxies.MxHashMap Map;
	private final java.lang.String EntryType;
	private final IMendixObject Entry;

	public JAVA_Hashmap_PutEntry(
		IContext context,
		IMendixObject _map,
		java.lang.String _entryType,
		IMendixObject _entry
	)
	{
		super(context);
		this.__Map = _map;
		this.Map = _map == null ? null : hashmap.proxies.MxHashMap.initialize(getContext(), _map);
		this.EntryType = _entryType;
		this.Entry = _entry;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MxHashMapImpl map = MxHashMapHelper.getHashMap(this.Map.getMendixObject());
		if(map == null) throw new Error("Cannot find hashmap");
		if(! map.getType().equals(this.EntryType)) throw new Error(String.format("Given entity type not the same as given on map initialization; given: %s; initialized: %s", this.EntryType, map.getType()));
		if(! this.Entry.isInstanceOf(this.EntryType)) throw new Error(String.format("Entry is not of type %s", this.EntryType));
		
		return map.getMap().put(this.Entry.getValue(getContext(), AbstractMxHashMapEntry.MemberNames.Key.toString()), this.Entry);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JAVA_Hashmap_PutEntry";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
