// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hashmap.actions;

import java.util.HashMap;
import com.mendix.systemwideinterfaces.core.IContext;
import hashmap.implementation.MxHashMapHelper;
import hashmap.implementation.MxHashMapImpl;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Removes the object related to key from the map and returns the object currently related to key. Provide the entity type so that the list is of the right type. If the entity type does not match the entity type given at creation of the map, this will throw a runtime error.
 */
public class JAVA_Hashmap_RemoveEntry extends UserAction<IMendixObject>
{
	/** @deprecated use Map.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Map;
	private final hashmap.proxies.MxHashMap Map;
	private final java.lang.String Key;
	private final java.lang.String EntryType;

	public JAVA_Hashmap_RemoveEntry(
		IContext context,
		IMendixObject _map,
		java.lang.String _key,
		java.lang.String _entryType
	)
	{
		super(context);
		this.__Map = _map;
		this.Map = _map == null ? null : hashmap.proxies.MxHashMap.initialize(getContext(), _map);
		this.Key = _key;
		this.EntryType = _entryType;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		MxHashMapImpl map = MxHashMapHelper.getHashMap(this.Map.getMendixObject());
		if(map == null) throw new Error("Cannot find hashmap");
		if(! map.getType().equals(this.EntryType)) throw new Error(String.format("Given entity type not the same as given on map initialization; given: %s; initialized: %s", this.EntryType, map.getType()));

		return map.getMap().remove(this.Key);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JAVA_Hashmap_RemoveEntry";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
