// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hashmap.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import hashmap.implementation.MxHashMapHelper;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Return the number of key-value mappings of the map
 */
public class JAVA_Hashmap_Size extends UserAction<java.lang.Long>
{
	/** @deprecated use Map.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Map;
	private final hashmap.proxies.MxHashMap Map;

	public JAVA_Hashmap_Size(
		IContext context,
		IMendixObject _map
	)
	{
		super(context);
		this.__Map = _map;
		this.Map = _map == null ? null : hashmap.proxies.MxHashMap.initialize(getContext(), _map);
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		return Long.valueOf(MxHashMapHelper.getHashMap(this.Map.getMendixObject()).getMap().size());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JAVA_Hashmap_Size";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
